spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mrsuser
    driverClassName: org.postgresql.Driver
    username: mrsuser
    password: mysecretpassword
    sql-script-encoding: UTF-8
    initialization-mode: always

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: TRACE